# fly.toml app configuration file generated for backend-damp-log-4605 on 2025-02-23T11:04:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-damp-log-4605'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.22.7'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
